# Generated by Django 4.1.5 on 2023-04-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('hobby', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='teacher/')),
            ],
        ),
    ]
